### ISSUE TITLE
 Add description and Features to README for Better Contributor Guidance

### ISSUE THREAD

**Issue by RaginiSharma01** [rahulharpal1603/CF-TopHacker#10]
Hi there! 👋

I noticed that the current README lacks some key details that could help new contributors get up to speed quickly. Specifically, it would be really helpful to:

List the technologies (tech stack) used in the project, so contributors know which languages, frameworks, or tools are involved.
Provide a brief section outlining the main features of the project. This would give contributors a clear understanding of what the project is about and what features are already implemented or need improvement.

**Comment by RaginiSharma01** [comment]
Assign this task to me I would improve the  readme documentation for better user understanding

**Comment by rahulharpal1603** [comment]
Can you also make a CONTRIBUTION.md file? Stating all the guidelines like setup instructions for the project.

**Comment by RaginiSharma01** [comment]
> Can you also make a CONTRIBUTION.md file? Stating all the guidelines like setup instructions for the project.

Yes I can do it

**Comment by rahulharpal1603** [comment]
Ok, I am assigning this issue.

**Comment by rahulharpal1603** [comment]
![image](https://github.com/user-attachments/assets/bc559f5a-19ee-4f69-b514-05412fc0a87e)


@RaginiSharma01 can we also have the above labels as dynamic? Currently, we need to update those labels manually after counting the number of active issues. There are many repositories which have these dynamic lables. 

You can get an idea from this repository: **https://github.com/layer5io/layer5**

**Comment by RaginiSharma01** [comment]
> ![image](https://private-user-images.githubusercontent.com/51887323/373849616-bc559f5a-19ee-4f69-b514-05412fc0a87e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMDc2MjQsIm5iZiI6MTcyODIwNzMyNCwicGF0aCI6Ii81MTg4NzMyMy8zNzM4NDk2MTYtYmM1NTlmNWEtMTllZS00ZjY5LWI1MTQtMDU0MTJmYzBhODdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDA5MzUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZmFhOGNjNzEyNTRmMzllNjY1NWRiNzhhM2Q1ZmExZjFiNjdiZGI5OWY1NjJkMjI2YjAwMjk0M2VhMjc5N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.34sBSR8-xqpN1iGFcQnoRuFFLaCAWsBojQQE384JSiU)
> 
> @RaginiSharma01 can we also have the above labels as dynamic? Currently, we need to update those labels manually after counting the number of active issues. There are many repositories which have these dynamic lables.
> 
> You can get an idea from this repository: **https://github.com/layer5io/layer5**

ok working on it

**Comment by rahulharpal1603** [comment]
@RaginiSharma01 any updates?

**Comment by RaginiSharma01** [comment]
@rahulharpal1603  
I have PR the changes please check
