### ISSUE TITLE
 Use Codeforces API to Fetch Hacks

### ISSUE THREAD

**Issue by karimali03** [rahulharpal1603/CF-TopHacker#11]
**Description:**
Currently, the hacks are fetched by parsing the HTML hacks page. I suggest using the Codeforces API to fetch hacks instead, as it will be more efficient.

**Benefits:**
- Reduces the overhead of parsing HTML.
- More reliable and less prone to changes in the HTML structure of the Codeforces website.
- Keep the existing HTML parsing code as an alternative if the API is down.

**Implementation Plan:**
- Create a function to fetch data from the Codeforces API
- use the HTML parsing method if the API is down.

**Comment by karimali03** [comment]
I can work on this issue

**Comment by rahulharpal1603** [comment]
When I was making this project, even I thought of it first, but counterintuitively, the API is slower. If you see the time to fetch all the data for this API request: https://codeforces.com/api/contest.standings?contestId=1985&showUnofficial=true, the time taken is too much, plus the JSON file is very big (around 50MB) which is very inefficient.

**Comment by karimali03** [comment]
Yeah, I found that the API is very slow, so the current approach is better.
