### ISSUE TITLE
[Feature]  Open Hack Details Window on Click in Hacks Table

### ISSUE THREAD

**Issue by karimali03** [rahulharpal1603/CF-TopHacker#12]
Add a feature to the CF-TopHacker Chrome extension to open a window with the IDs of hacks and links to these hacks pages when clicking on each cell in the hacks table.
- like the submissions window in standing
![image](https://github.com/user-attachments/assets/4c11e598-e077-48d0-a036-89b8a749c6cc)

- example of data in the window and the link attached to the hack id
![image](https://github.com/user-attachments/assets/9e3f46ac-f53d-4512-a808-0c6a94148c54)

I can work on this feature

**Comment by rahulharpal1603** [comment]
so when I double click on the +x : -y, the above window will open?

**Comment by karimali03** [comment]
Yes, and the window will contain all the user's successful and unsuccessful hacks on this problem.

**Comment by rahulharpal1603** [comment]
Nice. Go ahead!
