### ISSUE TITLE
Handling 'Verify You Are Human' Pages and API Errors Returning HTML Instead of JSON

### ISSUE THREAD

**Issue by karimali03** [rahulharpal1603/CF-TopHacker#16]
We are encountering issues with the Chrome extension for displaying the Hacks leaderboard on Codeforces. Specifically:

1. **Verify You Are Human Pages**: Sometimes, Codeforces displays a "Verify you are human" page before opening the requested URL. This results in the extension fetching the HTML of the verification page instead of the expected data.

![Screenshot from 2024-10-08 15-11-07](https://github.com/user-attachments/assets/4ca16882-1825-45c7-8055-201fcca8d4b7)
- Here I print to the console the page fetched and it appears that it is the waiting page
![Screenshot from 2024-10-08 15-26-51](https://github.com/user-attachments/assets/3f8680b3-0207-433b-ab7b-3d6313eac108)

2. **API Errors Returning HTML**: Occasionally, the Codeforces API returns an HTML page instead of JSON when fetching problem indices, especially after contests when the site experiences a high load.
![Screenshot from 2024-10-08 14-54-41](https://github.com/user-attachments/assets/42a9f760-a45d-412e-9a84-4191df954bf2)

These issues must be handled to ensure the extension functions correctly, even during high-load periods.

### Suggested Solution
- We can first try fetching the HTML and checking for CAPTCHA patterns. If HTML fails due to the CAPTCHA, we can fall back on the API, knowing it's slower but reliable.
- If the API has issues, like fetching problem indices, we can scrape them from the contest page or fetch them from the current user's standings page.

I can work on this issue

**Comment by rahulharpal1603** [comment]
The verify human page only appears 20-30 minutes after the contest. In my opinion, it would be too much of a work if the problem lasted 20-30 minutes.

**Comment by rahulharpal1603** [comment]
Also the CF API doesn't work until 20-30 minutes past contest.
