### ISSUE TITLE
Highlight the user's row(if present) in the hacks standings table and add support for Tourist title.

### ISSUE THREAD

**Issue by rahulharpal1603** [rahulharpal1603/CF-TopHacker#4]
Let's say the username is RahulHarpal. The current behaviour is: 

![image](https://github.com/user-attachments/assets/321f7aa1-c460-4f54-9e44-7112a6977490)

The row with my username is not highlighted. The ask is to highlight the row in this manner: 

![image](https://github.com/user-attachments/assets/945027e4-e9c6-4d2e-9f07-d0189703ddfe)

Also, since there is a new rank called "Tourist" on codeforces, the colour scheme for that is not supported yet. So this is required.

**Comment by Piyush-Goenka** [comment]
Hey @rahulharpal1603 ,
Please assign this issue to me .
I would like to work on this issue.

**Comment by rahulharpal1603** [comment]
> Hey @rahulharpal1603 ,
> Please assign this issue to me .
> I would like to work on this issue.

Sure @Piyush-Goenka, go for it!
